"""add expenses table

Revision ID: 21011b4e5373
Revises: 2b30a4eca58a
Create Date: 2026-01-17 20:57:50.641385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21011b4e5373'
down_revision = '2b30a4eca58a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('group_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paid_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_created_by'), 'expenses', ['created_by'], unique=False)
    op.create_index(op.f('ix_expenses_group_id'), 'expenses', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_group_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_created_by'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
