INVALID_SCHEMA = "INVALID_SCHEMA"
PUBLIC_SCHEMA = "public"
DB_NOT_UPTODATE = "DB_NOT_UPTODATE"
HEAD = "HEAD"
AUTHORIZATION = "Authorization"
INVALID_NOTIFICATION_TYPE = "INVALID_NOTIFICATION_TYPE"
TEMPLATE_FOLDER_NAME = "templates"
ATTACHMENT_FOLDER_NAME = "attachments"
TEMPLATE_FILE_EXTENTION = ".html.jinja"
USER_NOT_FOUND = "USER_NOT_FOUND"


#USER MANAGEMENT SERVICE RELATED CONSTANTS:
THE_USER_DETAILS_DOES_NOT_EXIST_FOR_THIS_ID = "THE_USER_DETAILS_DOES_NOT_EXIST_FOR_THIS_ID:"